/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmiesIndexRouteImport } from './routes/armies/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ArmiesArmyIdRouteImport } from './routes/armies/$armyId'
import { Route as MatchMatchIdPostMatchRouteImport } from './routes/match/$matchId/post-match'

const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmiesIndexRoute = ArmiesIndexRouteImport.update({
  id: '/armies/',
  path: '/armies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmiesArmyIdRoute = ArmiesArmyIdRouteImport.update({
  id: '/armies/$armyId',
  path: '/armies/$armyId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdPostMatchRoute = MatchMatchIdPostMatchRouteImport.update({
  id: '/match/$matchId/post-match',
  path: '/match/$matchId/post-match',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/references': typeof ReferencesRoute
  '/armies/$armyId': typeof ArmiesArmyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/armies/': typeof ArmiesIndexRoute
  '/match/$matchId/post-match': typeof MatchMatchIdPostMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/references': typeof ReferencesRoute
  '/armies/$armyId': typeof ArmiesArmyIdRoute
  '/admin': typeof AdminIndexRoute
  '/armies': typeof ArmiesIndexRoute
  '/match/$matchId/post-match': typeof MatchMatchIdPostMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/references': typeof ReferencesRoute
  '/armies/$armyId': typeof ArmiesArmyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/armies/': typeof ArmiesIndexRoute
  '/match/$matchId/post-match': typeof MatchMatchIdPostMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/references'
    | '/armies/$armyId'
    | '/admin/'
    | '/armies/'
    | '/match/$matchId/post-match'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/references'
    | '/armies/$armyId'
    | '/admin'
    | '/armies'
    | '/match/$matchId/post-match'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/references'
    | '/armies/$armyId'
    | '/admin/'
    | '/armies/'
    | '/match/$matchId/post-match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReferencesRoute: typeof ReferencesRoute
  ArmiesArmyIdRoute: typeof ArmiesArmyIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArmiesIndexRoute: typeof ArmiesIndexRoute
  MatchMatchIdPostMatchRoute: typeof MatchMatchIdPostMatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armies/': {
      id: '/armies/'
      path: '/armies'
      fullPath: '/armies/'
      preLoaderRoute: typeof ArmiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armies/$armyId': {
      id: '/armies/$armyId'
      path: '/armies/$armyId'
      fullPath: '/armies/$armyId'
      preLoaderRoute: typeof ArmiesArmyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId/post-match': {
      id: '/match/$matchId/post-match'
      path: '/match/$matchId/post-match'
      fullPath: '/match/$matchId/post-match'
      preLoaderRoute: typeof MatchMatchIdPostMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReferencesRoute: ReferencesRoute,
  ArmiesArmyIdRoute: ArmiesArmyIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArmiesIndexRoute: ArmiesIndexRoute,
  MatchMatchIdPostMatchRoute: MatchMatchIdPostMatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
